import 'dart:async';
import 'dart:convert';
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';
import 'firebase_options.dart';

const kSeed = Color(0xFF5B5BD6);

Future<void> _bg(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  var ready = false;
  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    FirebaseMessaging.onBackgroundMessage(_bg);
    ready = true;
  } catch (_) {}
  runApp(FamilyShoppingTest1App(firebaseReady: ready));
}

class FamilyShoppingTest1App extends StatefulWidget {
  final bool firebaseReady;
  const FamilyShoppingTest1App({super.key, required this.firebaseReady});
  @override State<FamilyShoppingTest1App> createState() => _FamilyShoppingTest1AppState();
}
class _FamilyShoppingTest1AppState extends State<FamilyShoppingTest1App> {
  Locale locale = const Locale('fa');
  bool dark = false;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async {
    final p = await SharedPreferences.getInstance();
    if (!mounted) return;
    setState(() { locale = Locale(p.getString('locale') ?? 'fa'); dark = p.getBool('dark') ?? false; });
  }
  Future<void> setLocale(Locale l) async { final p = await SharedPreferences.getInstance(); await p.setString('locale', l.languageCode); if (mounted) setState(() => locale = l); }
  Future<void> setDark(bool v) async { final p = await SharedPreferences.getInstance(); await p.setBool('dark', v); if (mounted) setState(() => dark = v); }
  @override Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false, title: 'لیست خرید خانواده تست1', locale: locale,
    supportedLocales: const [Locale('fa'), Locale('ar'), Locale('en')],
    localizationsDelegates: const [GlobalMaterialLocalizations.delegate, GlobalWidgetsLocalizations.delegate, GlobalCupertinoLocalizations.delegate],
    theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: kSeed), scaffoldBackgroundColor: const Color(0xFFF7F7FB), cardTheme: const CardThemeData(margin: EdgeInsets.zero, elevation: 0)),
    darkTheme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: kSeed, brightness: Brightness.dark), cardTheme: const CardThemeData(margin: EdgeInsets.zero, elevation: 0)),
    themeMode: dark ? ThemeMode.dark : ThemeMode.light,
    home: AuthGate(firebaseReady: widget.firebaseReady, onLocaleChanged: setLocale, onDarkChanged: setDark),
  );
}

class T {
  static const v = {
    'fa': {'app':'لیست خرید خانواده تست1','welcome':'خوش آمدید','login':'ورود به حساب','guest':'ورود مهمان','email':'ایمیل','password':'رمز عبور','name':'نام شما','create':'ساخت حساب','signIn':'ورود','logout':'خروج','home':'خانه','lists':'لیست‌ها','history':'تاریخچه','family':'خانواده','settings':'تنظیمات','addList':'لیست جدید','addItem':'افزودن کالا','item':'کالا','qty':'تعداد','save':'ذخیره','cancel':'لغو','empty':'هنوز چیزی اینجا نیست','sync':'همگام‌سازی','connected':'متصل','offline':'آفلاین','scan':'اسکن QR','showQr':'نمایش QR','profiles':'اعضای خانواده','categories':'دسته‌بندی‌ها','archive':'اتمام خرید','restore':'بازگردانی','delete':'حذف','search':'جستجو','language':'زبان','dark':'حالت تاریک','shoppingList':'لیست خرید','all':'همه','done':'انجام‌شده','new':'جدید','pair':'اتصال دستگاه','pairHint':'این کد را با دستگاه دوم اسکن کنید','pairOk':'دستگاه با موفقیت متصل شد','onlineSync':'همگام‌سازی اینترنتی','demo':'حالت محلی','passwordShort':'رمز باید حداقل ۶ کاراکتر باشد'},
    'ar': {'app':'مشترياتنا','welcome':'مرحباً','login':'تسجيل الدخول','guest':'الدخول كضيف','email':'البريد الإلكتروني','password':'كلمة المرور','name':'اسمك','create':'إنشاء حساب','signIn':'دخول','logout':'خروج','home':'الرئيسية','lists':'القوائم','history':'السجل','family':'العائلة','settings':'الإعدادات','addList':'قائمة جديدة','addItem':'إضافة منتج','item':'منتج','qty':'الكمية','save':'حفظ','cancel':'إلغاء','empty':'لا يوجد شيء هنا بعد','sync':'مزامنة','connected':'متصل','offline':'غير متصل','scan':'مسح QR','showQr':'عرض QR','profiles':'أفراد العائلة','categories':'التصنيفات','archive':'إنهاء التسوق','restore':'استعادة','delete':'حذف','search':'بحث','language':'اللغة','dark':'الوضع الداكن','shoppingList':'قائمة التسوق','all':'الكل','done':'تم','new':'جديد','pair':'ربط الجهاز','pairHint':'امسح هذا الرمز من الجهاز الثاني','pairOk':'تم الربط بنجاح','onlineSync':'المزامنة عبر الإنترنت','demo':'الوضع المحلي','passwordShort':'كلمة المرور ٦ أحرف على الأقل'},
    'en': {'app':'FamilyShoppingTest1','welcome':'Welcome','login':'Sign in','guest':'Continue as guest','email':'Email','password':'Password','name':'Your name','create':'Create account','signIn':'Sign in','logout':'Sign out','home':'Home','lists':'Lists','history':'History','family':'Family','settings':'Settings','addList':'New list','addItem':'Add item','item':'item','qty':'Quantity','save':'Save','cancel':'Cancel','empty':'Nothing here yet','sync':'Sync','connected':'Connected','offline':'Offline','scan':'Scan QR','showQr':'Show QR','profiles':'Family members','categories':'Categories','archive':'Finish shopping','restore':'Restore','delete':'Delete','search':'Search','language':'Language','dark':'Dark mode','shoppingList':'Shopping list','all':'All','done':'Done','new':'New','pair':'Connect device','pairHint':'Scan this code on the second device','pairOk':'Device connected','onlineSync':'Internet sync','demo':'Local mode','passwordShort':'Password must be at least 6 characters'},
  };
  static String get(BuildContext c, String k) => v[Localizations.localeOf(c).languageCode]?[k] ?? v['en']![k] ?? k;
}

class AppLogo extends StatelessWidget {
  final double size; const AppLogo({super.key, this.size = 52});
  @override Widget build(BuildContext context) => Container(width:size,height:size,decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF6C63FF),Color(0xFF42B7FF)]),borderRadius:BorderRadius.circular(size*.28),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.12),blurRadius:12,offset:const Offset(0,5))]),child:Icon(Icons.shopping_basket_rounded,size:size*.55,color:Colors.white));
}

enum Category { grocery, dairy, fruit, meat, bakery, household, pharmacy, other }
String catName(BuildContext c, Category x) { const fa=['سوپرمارکت','لبنیات','میوه و سبزی','پروتئین','نان و شیرینی','خانه','بهداشت','سایر']; const en=['Grocery','Dairy','Fruit & Veg','Protein','Bakery','Household','Health','Other']; const ar=['بقالة','ألبان','خضار وفواكه','لحوم','مخبوزات','المنزل','الصحة','أخرى']; final a=Localizations.localeOf(c).languageCode=='fa'?fa:Localizations.localeOf(c).languageCode=='ar'?ar:en; return a[x.index]; }
IconData catIcon(Category x) => [Icons.local_grocery_store,Icons.egg_alt,Icons.eco,Icons.set_meal,Icons.bakery_dining,Icons.home_repair_service,Icons.health_and_safety,Icons.category][x.index];

class Item { final String id,name; final int qty; final bool done; final Category category; Item({required this.id,required this.name,required this.qty,required this.done,required this.category}); Map<String,dynamic> map()=>{'id':id,'name':name,'qty':qty,'done':done,'category':category.index}; factory Item.from(Map<String,dynamic> m)=>Item(id:'${m['id']??''}',name:'${m['name']??''}',qty:(m['qty'] as num?)?.toInt()??1,done:m['done']??false,category:Category.values[((m['category'] as num?)?.toInt()??7).clamp(0,7)]); }
class BuyList { final String id,name; final List<Item> items; final DateTime updated; final bool archived; BuyList({required this.id,required this.name,required this.items,required this.updated,required this.archived}); Map<String,dynamic> map()=>{'id':id,'name':name,'items':items.map((e)=>e.map()).toList(),'updated':updated.toIso8601String(),'archived':archived}; factory BuyList.from(Map<String,dynamic> m)=>BuyList(id:'${m['id']}',name:'${m['name']}',items:((m['items'] as List?)??[]).map((e)=>Item.from(Map<String,dynamic>.from(e))).toList(),updated:DateTime.tryParse('${m['updated']}')??DateTime.now(),archived:m['archived']??false); }
class FamilyMember { final String name,email,role; FamilyMember(this.name,this.email,this.role); }

class Store {
  final bool firebaseReady; final FirebaseFirestore db=FirebaseFirestore.instance; String? familyId;
  Store(this.firebaseReady);
  Future<void> load() async { final p=await SharedPreferences.getInstance(); familyId=p.getString('familyId'); }
  Future<void> saveFamily(String id) async { familyId=id; final p=await SharedPreferences.getInstance(); await p.setString('familyId',id); }
  String id()=>DateTime.now().microsecondsSinceEpoch.toString()+Random().nextInt(999).toString();
  Future<User?> user() async { if(!firebaseReady)return null; if(FirebaseAuth.instance.currentUser==null) await FirebaseAuth.instance.signInAnonymously(); return FirebaseAuth.instance.currentUser; }
  Future<void> token() async { final u=await user(); if(u==null)return; try{await FirebaseMessaging.instance.requestPermission(alert:true,badge:true,sound:true); final t=await FirebaseMessaging.instance.getToken(); await db.collection('users').doc(u.uid).set({'token':t??'','name':u.displayName??'','updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));}catch(_){}}
  Future<String> createFamily() async { final u=await user(); if(u==null)throw Exception('Firebase'); final d=db.collection('families').doc(); await d.set({'memberIds':[u.uid],'createdAt':FieldValue.serverTimestamp()}); await saveFamily(d.id); await token(); return d.id; }
  Future<String> pairQr() async { final u=await user(); if(u==null||familyId==null)throw Exception('No family'); final code='${id()}${Random().nextInt(99999)}'; await db.collection('pairingCodes').doc(code).set({'familyId':familyId,'ownerUid':u.uid,'createdAt':FieldValue.serverTimestamp(),'expiresAt':Timestamp.fromDate(DateTime.now().add(const Duration(minutes:20)))}); return jsonEncode({'type':'family_pair','code':code}); }
  Future<void> join(String raw) async { final u=await user(); if(u==null)throw Exception('Firebase'); final j=jsonDecode(raw); final code=j['code']; final s=await db.collection('pairingCodes').doc(code).get(); if(!s.exists)throw Exception('QR invalid'); final d=s.data()!; if((d['expiresAt'] as Timestamp).toDate().isBefore(DateTime.now()))throw Exception('QR expired'); await db.collection('families').doc(d['familyId']).update({'memberIds':FieldValue.arrayUnion([u.uid]),'lastJoinCode':code}); await saveFamily(d['familyId']); await token(); }
  Stream<QuerySnapshot<Map<String,dynamic>>>? lists() => firebaseReady&&familyId!=null?db.collection('families').doc(familyId).collection('lists').orderBy('updatedAt',descending:true).snapshots():null;
  Future<void> put(BuyList l) async { if(!firebaseReady||familyId==null)return; final u=await user(); await db.collection('families').doc(familyId).collection('lists').doc(l.id).set({...l.map(),'updatedAt':FieldValue.serverTimestamp(),'updatedBy':u?.uid}); }
  Future<void> archive(BuyList l) async { final a=BuyList(id:l.id,name:l.name,items:l.items,updated:DateTime.now(),archived:true); await put(a); }
}

class AuthGate extends StatefulWidget { final bool firebaseReady; final ValueChanged<Locale> onLocaleChanged; final ValueChanged<bool> onDarkChanged; const AuthGate({super.key,required this.firebaseReady,required this.onLocaleChanged,required this.onDarkChanged}); @override State<AuthGate> createState()=>_AuthGateState(); }
class _AuthGateState extends State<AuthGate>{ User? user; bool loading=true; bool guestMode=false; StreamSubscription<User?>? authSub;
 @override void initState(){super.initState();_check(); if(widget.firebaseReady){authSub=FirebaseAuth.instance.authStateChanges().listen((u){if(mounted)setState((){user=u;});});}}
 Future<void> _check() async { if(widget.firebaseReady) user=FirebaseAuth.instance.currentUser; final p=await SharedPreferences.getInstance(); guestMode=p.getBool('guest')??false; if(user==null&&!guestMode){setState(()=>loading=false);return;} setState(()=>loading=false); }
 Future<void> guest() async { final p=await SharedPreferences.getInstance(); await p.setBool('guest',true); if(mounted)setState(()=>guestMode=true); }
 @override void dispose(){authSub?.cancel();super.dispose();}
 @override Widget build(BuildContext c)=>loading?const Scaffold(body:Center(child:CircularProgressIndicator())):((user!=null)||guestMode)?MainShell(firebaseReady:widget.firebaseReady,onLocaleChanged:widget.onLocaleChanged,onDarkChanged:widget.onDarkChanged):LoginPage(firebaseReady:widget.firebaseReady,onGuest:guest);
}

class LoginPage extends StatefulWidget { final bool firebaseReady; final VoidCallback onGuest; const LoginPage({super.key,required this.firebaseReady,required this.onGuest}); @override State<LoginPage> createState()=>_LoginPageState(); }
class _LoginPageState extends State<LoginPage>{ final email=TextEditingController(),pass=TextEditingController(),name=TextEditingController(); bool create=false,busy=false; Future<void> go() async { if(!widget.firebaseReady){widget.onGuest();return;} if(pass.text.length<6){_msg(T.get(context,'passwordShort'));return;} setState(()=>busy=true); try{ UserCredential c; if(create)c=await FirebaseAuth.instance.createUserWithEmailAndPassword(email:email.text.trim(),password:pass.text); else c=await FirebaseAuth.instance.signInWithEmailAndPassword(email:email.text.trim(),password:pass.text); if(name.text.trim().isNotEmpty)await c.user?.updateDisplayName(name.text.trim()); if(mounted)setState((){}); }catch(e){_msg(e.toString());}finally{if(mounted)setState(()=>busy=false);} }
 void _msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Column(children:[AppLogo(size:82),const SizedBox(height:20),Text('لیست خرید خانواده تست1',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('لیست خرید، همیشه همراه خانواده',textAlign:TextAlign.center),const SizedBox(height:34),Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Text(T.get(c,'welcome'),style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:18),if(create)TextField(controller:name,decoration:InputDecoration(labelText:T.get(c,'name'),prefixIcon:const Icon(Icons.person_outline))),if(create)const SizedBox(height:12),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:InputDecoration(labelText:T.get(c,'email'),prefixIcon:const Icon(Icons.email_outlined))),const SizedBox(height:12),TextField(controller:pass,obscureText:true,decoration:InputDecoration(labelText:T.get(c,'password'),prefixIcon:const Icon(Icons.lock_outline))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:go,child:Text(create?T.get(c,'create'):T.get(c,'signIn')))),TextButton(onPressed:busy?null:()=>setState(()=>create=!create),child:Text(create?T.get(c,'login'):T.get(c,'create'))),const Divider(),TextButton.icon(onPressed:widget.onGuest,icon:const Icon(Icons.person_outline),label:Text(T.get(c,'guest'))])))])))))); }
}

class MainShell extends StatefulWidget { final bool firebaseReady; final ValueChanged<Locale> onLocaleChanged; final ValueChanged<bool> onDarkChanged; const MainShell({super.key,required this.firebaseReady,required this.onLocaleChanged,required this.onDarkChanged}); @override State<MainShell> createState()=>_MainShellState(); }
class _MainShellState extends State<MainShell>{ int tab=0; late Store store; List<BuyList> lists=[]; List<BuyList> history=[]; List<FamilyMember> family=[FamilyMember('شما','—','مدیر')]; StreamSubscription? sub; bool initialized=false;
 @override void initState(){super.initState(); store=Store(widget.firebaseReady); _init();}
 Future<void> _init() async { final p=await SharedPreferences.getInstance(); final raw=p.getStringList('lists')??[]; lists=raw.map((e)=>BuyList.from(jsonDecode(e))).where((x)=>!x.archived).toList(); history=raw.map((e)=>BuyList.from(jsonDecode(e))).where((x)=>x.archived).toList(); store.familyId=p.getString('familyId'); initialized=true; if(widget.firebaseReady){store.familyId=p.getString('familyId'); if(store.familyId==null)try{await store.createFamily();}catch(_){} await store.token(); sub=store.lists()?.listen((s){final r=s.docs.map((d)=>BuyList.from({...d.data(),'id':d.id})).toList(); if(mounted)setState((){lists=r.where((x)=>!x.archived).toList();history=r.where((x)=>x.archived).toList();});});} if(mounted)setState((){}); }
 Future<void> save() async { final p=await SharedPreferences.getInstance(); await p.setStringList('lists',[...lists,...history].map((e)=>jsonEncode(e.map())).toList()); }
 Future<void> put(BuyList l) async { setState((){lists=[...lists.where((x)=>x.id!=l.id),l];}); await save(); await store.put(l); }
 Future<void> addList() async { final c=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:Text(T.get(context,'addList')),content:TextField(controller:c,autofocus:true,decoration:InputDecoration(labelText:T.get(context,'shoppingList'))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text(T.get(context,'cancel'))),FilledButton(onPressed:()=>Navigator.pop(context,true),child:Text(T.get(context,'save')))])); if(ok==true&&c.text.trim().isNotEmpty){final l=BuyList(id:store.id(),name:c.text.trim(),items:[],updated:DateTime.now(),archived:false); await put(l);openList(l);} }
 void openList(BuyList l)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ListEditor(list:l,onChanged:put,onArchive:(x)async{await store.archive(x);setState(()=>{lists.removeWhere((a)=>a.id==x.id);history=[...history,x.copyArchived()]});await save();}))).then((_)=>_init());
 Future<void> showQr() async {if(!widget.firebaseReady)return _msg(T.get(context,'demo')); try{final s=await store.pairQr();if(mounted)showDialog(context:context,builder:(_)=>AlertDialog(title:Text(T.get(context,'pair')),content:Column(mainAxisSize:MainAxisSize.min,children:[QrImageView(data:s,size:230),const SizedBox(height:12),Text(T.get(context,'pairHint'),textAlign:TextAlign.center)]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text(T.get(context,'done')))]));}catch(e){_msg('$e');}}
 Future<void> scan() async {if(!widget.firebaseReady)return _msg(T.get(context,'demo'));final raw=await Navigator.push<String>(context,MaterialPageRoute(builder:(_)=>const Scanner()));if(raw==null)return;try{await store.join(raw);_msg(T.get(context,'pairOk'));}catch(e){_msg('$e');}}
 void _msg(String x)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));
 @override void dispose(){sub?.cancel();super.dispose();}
 @override Widget build(BuildContext c){final pages=[HomeTab(lists:lists,onOpen:openList,onNew:addList),ListsTab(lists:lists,onOpen:openList,onNew:addList),HistoryTab(history:history,onRestore:(x)async{final n=BuyList(id:x.id,name:x.name,items:x.items.map((i)=>Item(id:i.id,name:i.name,qty:i.qty,done:false,category:i.category)).toList(),updated:DateTime.now(),archived:false);await put(n);setState(()=>history.removeWhere((h)=>h.id==x.id));await save();}),FamilyTab(family:family,onQr:showQr,onScan:scan),SettingsTab(onLocale:widget.onLocaleChanged,onDark:widget.onDarkChanged)];return Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:[NavigationDestination(icon:const Icon(Icons.home_outlined),selectedIcon:const Icon(Icons.home),label:T.get(c,'home')),NavigationDestination(icon:const Icon(Icons.checklist_outlined),selectedIcon:const Icon(Icons.checklist),label:T.get(c,'lists')),NavigationDestination(icon:const Icon(Icons.history),label:T.get(c,'history')),NavigationDestination(icon:const Icon(Icons.groups_outlined),label:T.get(c,'family')),NavigationDestination(icon:const Icon(Icons.settings_outlined),label:T.get(c,'settings'))]));}
}

extension BuyListCopy on BuyList { BuyList copyArchived()=>BuyList(id:id,name:name,items:items,updated:DateTime.now(),archived:true); }

class HomeTab extends StatelessWidget {final List<BuyList> lists;final void Function(BuyList) onOpen;final VoidCallback onNew;const HomeTab({super.key,required this.lists,required this.onOpen,required this.onNew});@override Widget build(BuildContext c){final active=lists.take(3).toList();return SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Row(children:[const AppLogo(size:48),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(T.get(c,'welcome'),style:Theme.of(c).textTheme.bodyMedium),Text(T.get(c,'app'),style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900))])),IconButton(onPressed:onNew,icon:const Icon(Icons.add_circle_rounded,size:34))]),const SizedBox(height:24),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF6C63FF),Color(0xFF42B7FF)]),borderRadius:BorderRadius.circular(28)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(T.get(c,'shoppingList'),style:const TextStyle(color:Colors.white70)),const SizedBox(height:8),Text('${lists.length} ${T.get(c,'lists')}',style:const TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:16),FilledButton.tonalIcon(onPressed:onNew,icon:const Icon(Icons.add),label:Text(T.get(c,'addList')))])),const SizedBox(height:24),Text(T.get(c,'lists'),style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:10),if(active.isEmpty)Card(child:Padding(padding:const EdgeInsets.all(24),child:Center(child:Text(T.get(c,'empty'))))) else ...active.map((l)=>ListTileCard(list:l,onTap:()=>onOpen(l))) ]));}}
class ListsTab extends StatelessWidget {final List<BuyList> lists;final void Function(BuyList) onOpen;final VoidCallback onNew;const ListsTab({super.key,required this.lists,required this.onOpen,required this.onNew});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Row(children:[Expanded(child:Text(T.get(c,'lists'),style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900))),FilledButton.icon(onPressed:onNew,icon:const Icon(Icons.add),label:Text(T.get(c,'new')))]),const SizedBox(height:14),...lists.map((l)=>ListTileCard(list:l,onTap:()=>onOpen(l))) ]));}
class ListTileCard extends StatelessWidget{final BuyList list;final VoidCallback onTap;const ListTileCard({super.key,required this.list,required this.onTap});@override Widget build(BuildContext c){final done=list.items.where((x)=>x.done).length;return Card(margin:const EdgeInsets.only(bottom:12),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:Theme.of(c).colorScheme.primaryContainer,borderRadius:BorderRadius.circular(15)),child:Icon(Icons.shopping_basket_rounded,color:Theme.of(c).colorScheme.primary)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(list.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),const SizedBox(height:5),Text('$done/${list.items.length} ${T.get(c,'done')}') ])),const Icon(Icons.chevron_right_rounded)])));}}

class ListEditor extends StatefulWidget{final BuyList list;final Future<void> Function(BuyList) onChanged;final Future<void> Function(BuyList) onArchive;const ListEditor({super.key,required this.list,required this.onChanged,required this.onArchive});@override State<ListEditor> createState()=>_ListEditorState();}
class _ListEditorState extends State<ListEditor>{late BuyList l;String filter='all';@override void initState(){super.initState();l=widget.list;} Future<void> add() async {final n=TextEditingController();final q=TextEditingController(text:'1');Category cat=Category.grocery;final ok=await showDialog<bool>(context:context,builder:(_)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:Text(T.get(c,'addItem')),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,autofocus:true,decoration:InputDecoration(labelText:T.get(c,'item'))),const SizedBox(height:12),TextField(controller:q,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:T.get(c,'qty'))),const SizedBox(height:12),DropdownButtonFormField<Category>(value:cat,items:Category.values.map((x)=>DropdownMenuItem(value:x,child:Row(children:[Icon(catIcon(x),size:20),const SizedBox(width:8),Text(catName(c,x))]))).toList(),onChanged:(x)=>set(()=>cat=x??cat),decoration:InputDecoration(labelText:T.get(c,'categories')))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:Text(T.get(c,'cancel'))),FilledButton(onPressed:()=>Navigator.pop(c,true),child:Text(T.get(c,'save')))])));if(ok==true&&n.text.trim().isNotEmpty){final item=Item(id:DateTime.now().microsecondsSinceEpoch.toString(),name:n.text.trim(),qty:int.tryParse(q.text)??1,done:false,category:cat);setState(()=>l=BuyList(id:l.id,name:l.name,items:[...l.items,item],updated:DateTime.now(),archived:false));await widget.onChanged(l);}}
 Future<void> toggle(Item x){final items=l.items.map((i)=>i.id==x.id?Item(id:i.id,name:i.name,qty:i.qty,done:!i.done,category:i.category):i).toList();l=BuyList(id:l.id,name:l.name,items:items,updated:DateTime.now(),archived:false);setState((){});return widget.onChanged(l);}
 @override Widget build(BuildContext c){final shown=l.items.where((x)=>filter=='all'||(filter=='done'&&x.done)||(filter=='todo'&&!x.done)).toList();return Scaffold(appBar:AppBar(title:Text(l.name),actions:[IconButton(onPressed:()=>widget.onArchive(l),icon:const Icon(Icons.archive_outlined))]),floatingActionButton:FloatingActionButton.extended(onPressed:add,icon:const Icon(Icons.add),label:Text(T.get(c,'addItem'))),body:ListView(padding:const EdgeInsets.fromLTRB(16,10,16,100),children:[SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[ChoiceChip(label:Text(T.get(c,'all')),selected:filter=='all',onSelected:(_)=>setState(()=>filter='all')),const SizedBox(width:8),ChoiceChip(label:Text(T.get(c,'done')),selected:filter=='done',onSelected:(_)=>setState(()=>filter='done')),const SizedBox(width:8),ChoiceChip(label:Text(T.get(c,'new')),selected:filter=='todo',onSelected:(_)=>setState(()=>filter='todo'))])),const SizedBox(height:14),if(shown.isEmpty)Padding(padding:const EdgeInsets.all(50),child:Center(child:Text(T.get(c,'empty')))) else ...shown.map((x)=>Card(margin:const EdgeInsets.only(bottom:9),child:ListTile(leading:CircleAvatar(child:Icon(catIcon(x.category),size:19)),title:Text(x.name,style:TextStyle(decoration:x.done?TextDecoration.lineThrough:null,fontWeight:FontWeight.w600)),subtitle:Text(catName(c,x.category)),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text('×${x.qty}',style:const TextStyle(fontWeight:FontWeight.bold)),Checkbox(value:x.done,onChanged:(_)=>toggle(x))])))) ]));}}

class HistoryTab extends StatelessWidget{final List<BuyList> history;final Future<void> Function(BuyList) onRestore;const HistoryTab({super.key,required this.history,required this.onRestore});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Text(T.get(c,'history'),style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:16),if(history.isEmpty)Center(child:Padding(padding:const EdgeInsets.all(60),child:Text(T.get(c,'empty')))) else ...history.map((l)=>Card(margin:const EdgeInsets.only(bottom:10),child:ListTile(leading:const CircleAvatar(child:Icon(Icons.check)),title:Text(l.name),subtitle:Text('${l.items.length} ${T.get(c,'item')}'),trailing:IconButton(onPressed:()=>onRestore(l),icon:const Icon(Icons.restore))))]));}
class FamilyTab extends StatelessWidget{final List<FamilyMember> family;final VoidCallback onQr,onScan;const FamilyTab({super.key,required this.family,required this.onQr,required this.onScan});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Text(T.get(c,'family'),style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:16),Card(child:Column(children:family.map((m)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(m.name),subtitle:Text('${m.email} • ${m.role}')).toList())),),const SizedBox(height:20),Text(T.get(c,'profiles'),style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:10),Row(children:[Expanded(child:FilledButton.icon(onPressed:onQr,icon:const Icon(Icons.qr_code_2),label:Text(T.get(c,'showQr')))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:onScan,icon:const Icon(Icons.qr_code_scanner),label:Text(T.get(c,'scan'))))]) ]));}
class SettingsTab extends StatelessWidget{final ValueChanged<Locale> onLocale;final ValueChanged<bool> onDark;const SettingsTab({super.key,required this.onLocale,required this.onDark});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Text(T.get(c,'settings'),style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:16),Card(child:Column(children:[ListTile(leading:const Icon(Icons.language),title:Text(T.get(c,'language')),trailing:DropdownButton<String>(value:Localizations.localeOf(c).languageCode,items:const [DropdownMenuItem(value:'fa',child:Text('فارسی')),DropdownMenuItem(value:'ar',child:Text('العربية')),DropdownMenuItem(value:'en',child:Text('English'))],onChanged:(v){if(v!=null)onLocale(Locale(v));})),const Divider(height:1),SwitchListTile(secondary:const Icon(Icons.dark_mode_outlined),title:Text(T.get(c,'dark')),value:Theme.of(c).brightness==Brightness.dark,onChanged:onDark)]))]));}

class Scanner extends StatefulWidget{const Scanner({super.key});@override State<Scanner> createState()=>_ScannerState();}class _ScannerState extends State<Scanner>{bool done=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(T.get(c,'scan'))),body:MobileScanner(onDetect:(capture){if(done)return;final s=capture.barcodes.isNotEmpty?capture.barcodes.first.rawValue:null;if(s!=null){done=true;Navigator.pop(c,s);}}));}
